import pandas as pd

file_path = '/content/true-size-of-countries-2024.csv'
data = pd.read_csv(file_path)

data.fillna(0, inplace=True)

translation_dict = {
    "country": "Страна",
    "area": "Площадь",
    "areaMi": "Площадь (мили)",
    "landAreaKm": "Площадь суши (км2)",
    "ActualSizeOfCountriesTotalWaterKm": "Общая площадь воды (км2)",
    "ActualSizeOfCountriesPercentOfTerritoryWater": "Процент воды в территории",
    # Add more translations as needed for other columns
}

data.rename(columns=translation_dict, inplace=True)

country_translation_dict = {
    "India": "Индия",
    "China": "Китай",
    "United States": "Соединённые Штаты",
    "Indonesia": "Индонезия",
    "Pakistan": "Пакистан",
    "Nigeria": "Нигерия",
    "Brazil": "Бразилия",
    "Bangladesh": "Бангладеш",
    "Russia": "Россия",
    "Ethiopia": "Эфиопия",
    "Mexico": "Мексика",
    "Japan": "Япония", 
    "Egypt": "Египет",
    "Philippines": "Филиппины",
    "DR Congo": "ДРК",
    "Vietnam": "Вьетнам",
    "Iran": "Иран",
    "Turkey	": "Турция",
    "Germany": "Германия",
    "Thailand": "Тайланд",
    "United Kingdom": "Велико­британия",
    "Tanzania": "Танзания",
    "France": "Франция",
    "South Africa": "ЮАР", 
    "Italy": "Италия",
    "Kenya": "Кения",
    "Myanmar": "Мьянма",
    "Colombia": "Колумбия",
    "South Korea": "Южная Корея",
    "Sudan": "Судан",
    "Uganda": "Уганда",
    "Spain": "Испания",
    "Algeria": "Алжир",
    "Iraq": "Ирак",
    "Argentina": "Аргентина",
    "Afghanistan": "Афганистан",
    "Yemen": "Йемен",
    "Canada": "Канада",
    "Poland": "Польша",
    "Morocco": "Марокко",
    "Angola": "Ангола",
    "Ukraine": "Украина",
    "Uzbekistan": "Узбекистан",
    "Malaysia": "Малайзия",
    "Mozambique": "Мозамбик",
    "Ghana": "Гана",
    "Peru": "Перу",
    "Saudi Arabia": "Саудовская Аравия",
    "Madagascar": "Мадагаскар",
    "Ivory Coast": "Кот-д'Ивуар",
    "Nepal": "Непал",
    "Cameroon": "Камерун",
    "Venezuela": "Венесуэла",
    "Niger": "Нигер",
    "Australia": "Австралия",
    "North Korea": "Северная Корея",
    "Syria": "Сирия",
    "Mali": "Мали",
    "Burkina Faso": "Буркина-Фасо",
    "Taiwan": "Тайвань",
    "Sri Lanka": "Шри-Ланка",
    "Malawi": "Малави",
    "Zambia": "Замбия",
    "Kazakhstan": "Казахстан",
    "Chad": "Чад",
    "Chile": "Чили",
    "Romania": "Румыния",
    "Somalia": "Сомали",
    "Senegal": "Сенегал",
    "Guatemala": "Гватемала",
    "Netherlands": "Нидерланды",
    "Ecuador": "Эквадор",
    "Cambodia": "Камбоджа",
    "Zimbabwe": "Зимбабве",
    "Guinea": "Гвинея",
    "Benin": "Бенин",
    "Rwanda": "Руанда",
    "Burundi": "Бурунди",
    "Bolivia": "Боливия",
    "Tunisia": "Тунис",
    "South Sudan": "Южный Судан",
    "Haiti": "Гаити",
    "Belgium": "Бельгия",
    "Jordan": "Иордания",
    "Dominican Republic": "Доминиканская Республика",
    "United Arab Emirates": "Объединённые Арабские Эмираты",
    "Cuba": "Куба",
    "Honduras": "Гондурас",
    "Czech Republic": "Чехия",
    "Sweden": "Швеция",
    "Tajikistan": "Таджикистан",
    "Papua New Guinea": "Папуа - Новая Гвинея",
    "Portugal": "Португалия",
    "Azerbaijan": "Азербайджан",
    "Greece": "Греция",
    "Hungary": "Венгрия",
    "Togo": "Того",
    "Israel": "Израиль",
    "Austria": "Австрия",
    "Belarus": "Беларусь",
    "Switzerland": "Швейцария",
    "Sierra Leone": "Сьерра-Леоне",
    "Laos": "Лаос",
    "Turkmenistan": "Туркменистан",
    "Hong Kong": "Гонконг",
    "Libya": "Ливия",
    "Kyrgyzstan": "Киргизия",
    "Paraguay": "Парагвай",
    "Nicaragua": "Никарагуа",
    "Bulgaria": "Болгария",
    "Serbia": "Сербия",
    "El Salvador": "Сальвадор",
    "Republic of the Congo": "Республика Конго",
    "Denmark": "Дания",
    "Singapore": "Сингапур",
    "Lebanon": "Ливан",
    "Finland": "Финляндия",
    "Liberia": "Либерия",
    "Norway": "Норвегия",
    "Slovakia": "Словакия",
    "Palestine": "Палестина",
    "Central African Republic": "Центральноафриканская Республика",
    "Oman": "Оман",
    "Ireland": "Ирландия",
    "New Zealand": "Новая Зеландия",
    "Mauritania": "Мавритания",
    "Costa Rica": "Коста-Рика",
    "Kuwait": "Кувейт",
    "Panama": "Панама",
    "Croatia": "Хорватия",
    "Georgia": "Грузия",
    "Eritrea": "Эритрея",
    "Mongolia": "Монголия",
    "Uruguay": "Уругвай",
    "Puerto Rico": "Пуэрто-Рико",
    "Bosnia and Herzegovina": "Босния и Герцеговина",
    "Qatar": "Катар",
    "Moldova": "Молдова",
    "Namibia": "Намибия",
    "Armenia": "Армения",
    "Lithuania": "Литва",
    "Jamaica": "Ямайка",
    "Albania": "Албания",
    "Gambia": "Гамбия",
    "Gabon": "Габон",
    "Botswana": "Ботсвана",
    "Lesotho": "Лесото",
    "Guinea-Bissau": "Гвинея-Бисау",
    "Slovenia": "Словения",
    "Equatorial Guinea": "Экваториальная Гвинея",
    "Latvia": "Латвия",
    "North Macedonia": "Северная Македония",
    "Bahrain": "Бахрейн",
    "Trinidad and Tobago": "Тринидад и Тобаго",
    "Timor-Leste": "Тимор-Лешти",
    "Estonia": "Эстония",
    "Cyprus": "Кипр",
    "Mauritius": "Маврикий",
    "Eswatini": "Эсватини",
    "Djibouti": "Джибути",
    "Fiji": "Фиджи",
    "Reunion": "Реюньон",
    "Comoros": "Коморские острова",
    "Guyana": "Гайана",
    "Solomon Islands": "Соломоновы Острова",
    "Bhutan": "Бутан",
    "Macau": "Макао",
    "Luxembourg": "Люксембург",
    "Montenegro": "Черногория",
    "Suriname": "Суринам",
    "Western Sahara": "Западная Сахара",
    "Malta": "Мальта",
    "Maldives": "Мальдивы",
    "Cape Verde": "Кабо-Верде",
    "Brunei": "Бруней",
    "Belize": "Белиз",
    "Bahamas": "Багамы",
    "Iceland": "Исландия",
    "Guadeloupe": "Гваделупа",
    "Martinique": "Мартиника",
    "Vanuatu": "Вануату",
    "Mayotte": "Майотта",
    "French Guiana": "Французская Гвиана",
    "New Caledonia": "Новая Каледония",
    "Barbados": "Барбадос",
    "French Polynesia": "Французская Полинезия",
    "Sao Tome and Principe": "Сан-Томе и Принсипи",
    "Samoa": "Самоа",
    "Curacao": "Кюрасао",
    "Saint Lucia": "Сент-Люсия",
    "Guam": "Гуам",
    "Kiribati": "Кирибати",
    "Seychelles": "Сейшельские острова",
    "Grenada": "Гренада",
    "Micronesia": "Микронезия",
    "Aruba": "Аруба",
    "Tonga": "Тонга",
    "Jersey": "Джерси",
    "Saint Vincent and the Grenadines": "Сент-Винсент и Гренадины",
    "Antigua and Barbuda": "Антигуа и Барбуда", 
    "British Virgin Islands": "Британские Виргинские острова",
    "Isle of Man": "Остров Мэн",
    "Andorra": "Андорра",
    "Cayman Islands": "Каймановы острова",
    "Dominica": "Доминика",
    "Bermuda": "Бермуды",
    "Guernsey": "Гернси",
    "Greenland": "Гренландия",
    "Faroe Islands": "Фарерские острова",
    "Saint Kitts and Nevis": "Сент-Китс и Невис",
    "American Samoa": "Американское Самоа",
    "Turks and Caicos Islands": "Туркские и Кайкосские острова",
    "Northern Mariana Islands": "Северные Марианские острова",
    "Sint Maarten": "Синт-Мартен",
    "Liechtenstein": "Лихтенштейн",
    "British Virgin Islands": "Британские Виргинские острова",
    "Gibraltar": "Гибралтар",
    "Monaco": "Монако",
    "Marshall Islands": "Маршалловы острова",
    "San Marino": "Сан-Марино",
    "Saint Martin": "Сент-Мартен",
    "Palau": "Палау",
    "Anguilla": "Ангуилья",
    "Cook Islands": "Острова Кука",
    "Nauru": "Науру",
    "Wallis and Futuna": "Уоллис и Футуна",
    "Saint Barthelemy": "Сен-Бартельми",
    "Tuvalu": "Тувалу",
    "Saint Pierre and Miquelon": "Сен-Пьер и Микелон",
    "Montserrat": "Монтсеррат",
    "Falkland Islands": "Фолклендские острова",
    "Tokelau": "Токелау",
    "Niue": "Ниуэ",
    "Vatican City": "Ватикан", 
    "United States Virgin Islands": "Виргинские острова США"
}

data['Страна'] = data['Страна'].map(country_translation_dict).fillna(data['Страна'])

data.to_csv('перевод.csv', index=False, encoding='utf-8')

print("Данные сохранены в файл 'перевод.csv'")
